### ISSUE TITLE
Feature request: Add support to self hosted gitlab

### ISSUE THREAD

**Issue by tux-tn** [ospfranco/cidemon#1]
Hello Oscar,

I discovered your project today on ProductHunt, the idea is great and the interface is simple and user-friendly 👏 👏 👏 
I suggest adding support to self-hosted Gitlab, the only difference would be requesting host domain in addition to the api key when adding gitlab and using that domain for api calls.

If you agree with the idea i can try to work on it !

**Comment by ospfranco** [comment]
Yeah! sounds good to me!

Just as some general guidelines:

You should modify the INode type (`typings.d.ts`) to contain a baseUrl type or something like that, most of the logic you will need to modify is on `Node.store.ts` and `Api.store.ts`, then ofc you need to take care of the UI (`AddToken.container.tsx`)

Code is a bit messy 🙈 I rewrote the app several times and fixed bugs haphazardly, but will gladly assist in w/e you need

**Comment by ospfranco** [comment]
I've cleaned the code a bit (at least deleted a bunch of unused components code), the fetching code is still a bit messy, but should be easier now.

Also, I made a mistake, you don't need to modify the `INode` type, but the `IToken` type, with an optional url field

**Comment by tux-tn** [comment]
@ospfranco thank you for the explanation, i will start working on the PR tonight or tomorrow, will probably ping you if there is something i don't understand or if i have any question !
